#!/usr/bin/env bash
# Áp TẤT CẢ bản vá theo đúng thứ tự tích luỹ. Sinh tự động — đừng sửa tay.
# Dùng: bash patches/apply-all.sh   (chạy từ gốc repo)
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

git apply "patches/01-anti-confabulation/01.patch"
git apply "patches/07-deterministic/07.patch"
git apply "patches/07-deterministic/07b.patch"
git apply "patches/02-anti-hallucination/02.patch"
git apply "patches/03-injection/03a.patch"
git apply "patches/03-injection/03a-2.patch"
git apply "patches/03-injection/03b.patch"
git apply "patches/03-injection/03b-2.patch"
git apply "patches/04-coverage-meaning/04.patch"
git apply "patches/05-confidence-interval/05.patch"
git apply "patches/05-confidence-interval/05-2.patch"
git apply "patches/06-evidence-probe-first/06.patch"
git apply "patches/06-evidence-probe-first/06b.patch"
git apply "patches/08-data-policy/08.patch"
git apply "patches/09-authorization/09.patch"
git apply "patches/10-personalization/10.patch"
git apply "patches/03-injection/03a-3.patch"
git apply "patches/08-data-policy/08b.patch"
git apply "patches/10-personalization/10b.patch"
git apply "patches/11-observability/11.patch"
git apply "patches/11-observability/11-2.patch"
git apply "patches/11-observability/11-2b.patch"
git apply "patches/11-observability/11-3.patch"
git apply "patches/08-data-policy/08c.patch"
git apply "patches/10-personalization/10c.patch"
git apply "patches/10-personalization/10d.patch"
git apply "patches/03-injection/T-runner.patch"
git apply "patches/03-injection/T-project.patch"
git apply "patches/08-data-policy/T-redaction.patch"
git apply "patches/10-personalization/T-persona.patch"
git apply "patches/02-anti-hallucination/T-retrieval.patch"
git apply "patches/06-evidence-probe-first/T-claims.patch"
git apply "patches/11-observability/T-tracing.patch"
git apply "patches/01-anti-confabulation/chat-01.patch"
git apply "patches/07-deterministic/chat-07.patch"
git apply "patches/06-evidence-probe-first/chat-06.patch"
echo "Đã áp 36 bản vá."
